// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvrQH2Lug-wUYHM6cRpzSbHdq-nUDdM-I',
    appId: '1:618974683566:web:f8db92cfd2259b1853683f',
    messagingSenderId: '618974683566',
    projectId: 'loginscreen-bfad5',
    authDomain: 'loginscreen-bfad5.firebaseapp.com',
    storageBucket: 'loginscreen-bfad5.appspot.com',
    measurementId: 'G-GGMC45XET8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFjP3X7VIsM_14oCoTL7nJqmuFp3Up6o',
    appId: '1:618974683566:android:6ad1ef4c7fff6a7e53683f',
    messagingSenderId: '618974683566',
    projectId: 'loginscreen-bfad5',
    storageBucket: 'loginscreen-bfad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQk3Gjj9H5GaKK_Zg0qdUP2Z-I9jmkROc',
    appId: '1:618974683566:ios:f3dd0b43300f26b153683f',
    messagingSenderId: '618974683566',
    projectId: 'loginscreen-bfad5',
    storageBucket: 'loginscreen-bfad5.appspot.com',
    iosClientId: '618974683566-5i9r2f3l7gceqrb2dmto967d272oucud.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQk3Gjj9H5GaKK_Zg0qdUP2Z-I9jmkROc',
    appId: '1:618974683566:ios:f3dd0b43300f26b153683f',
    messagingSenderId: '618974683566',
    projectId: 'loginscreen-bfad5',
    storageBucket: 'loginscreen-bfad5.appspot.com',
    iosClientId: '618974683566-5i9r2f3l7gceqrb2dmto967d272oucud.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginScreen',
  );
}
